### ISSUE TITLE
Suport for CocAction ?

### ISSUE THREAD

**Issue by dagadbm** [antoinemadec/coc-fzf#1]
Would it make sense to support a way to search through all coc actions / commands you can do with coc?

**Comment by antoinemadec** [comment]
@dagadbm , you are talking about the equivalient of ```CocList actions``` right?
I am not using ```actions``` very often, but it should be doable using
```vim
let actions = CocAction('codeActions') " to get the available actions
call CocAction('codeAction', command) " to apply user selected action
```

I think this is a great idea to add this, would you be OK to try adding this?
You can look at [services.vim](https://github.com/antoinemadec/coc-fzf/blob/master/autoload/coc_fzf/services.vim) for inspiration, it should follow the same structure without the need to re-enter (ie: no "first_call" stuff).

Thanks,
Antoine

**Comment by dagadbm** [comment]
i think im talking about two different things but my coc knowledge is still low:

the actions i think you can already do with <Plug>(coc-codeaction) right?

im talking about having a list where i can search all possible coc commands for example "tsserver.organizeImports" or "Prettier.formatFile" "eslint.executeAutofix", etc

so maybe this is two different commands?

**Comment by dagadbm** [comment]
also doesnt this do what i say ?
 https://github.com/iamcco/coc-actions

**Comment by antoinemadec** [comment]
> im talking about having a list where i can search all possible coc commands for example "tsserver.organizeImports" or "Prettier.formatFile" "eslint.executeAutofix", etc

I think you are talking about ```CocList commands```.
https://github.com/iamcco/coc-actions will provides ```CocList actions``` in a **completion menu**.

The goal of this plugin is to provide ```CocList``` sources using FZF, not to add ```CocList``` sources in a completion menu.
That being said both ```CocList commands``` and ```CocList actions``` would be interesting to add to this plugin :smiley:

**Comment by antoinemadec** [comment]
d8c9f1c11072b8b68db7a9779203c9e3f99cacd6 added the equivalent of ```CocList commands```.
You can use this to get inspired for the ```CocList actions``` if you are planning to add this feature.

**Comment by wookayin** [comment]
Awesome!
