### ISSUE TITLE
Preview for outline(document symbols) list

### ISSUE THREAD

**Issue by vatosarmat** [antoinemadec/coc-fzf#100]
Thanks you for the plugin and for preview feature in workspace symbols list in particular. How about to support it also for document symbols list? Some projects have very big source files with ~10k lines and a lot of definitions and it would be nice to quickly overview them in the list and preview interesting ones without scrolling through the whole file and reopening the list.

**Comment by antoinemadec** [comment]
Sounds like a great idea. Could you please create a PR ?
