### ISSUE TITLE
How to exclude unwanted files/folders from the "CocFzfList symbols" resutl?

### ISSUE THREAD

**Issue by m1t0z** [antoinemadec/coc-fzf#102]
Hi!

First of all thanks a lot for such a great plugin!

Wanted to ask whether it's possible to exclude unwanted files/folders from the `:CocFzfList symbols` result?

Initially i thought that 'coc-fzf' plugin uses the `list.source.symbols.excludes` coc-setting but a simple experiment refuted this assumption.

Do i need to setup my fzf installation accordingly (e.g by adjusting `FZF_DEFAULT_COMMAND`, `~/.gitignore`, etc) or there is another way which will affect only `:CocFzfList symbols` results only?

Br,
Dmitry

**Comment by antoinemadec** [comment]
@m1t0z , thanks for the kind words!

If I understand correctly, you are saying that:

1. ```:FzfList symbols``` uses ```list.source.symbols.excludes``` to exclude files from its search
2. ```:CocFzfList symbols``` does not use ```list.source.symbols.excludes``` to exclude files from its search

This is unexpected, ```CocFzfList symbols``` should behave like ```FzfList symbols```.
Indeed, internally coc-fzf calls the coc's function ```CocAction('getWorkspaceSymbols', 'foo')```

Could you please provide me with:

- a **minimal** vimrc
- a **minimal** coc-settings.json
- a testcase with ```CocFzf symbols``` and ```FzfList symbols``` commands (looking in python files for instance)

**Comment by antoinemadec** [comment]
@m1t0z OK, I was able to identify and fix the issue.
The exclude is handled outside ```CocAction('getWorkspaceSymbols', 'foo')```, so I had to add it in my python script.

**Could you please update coc-fzf and tell me if this fixes your issue ?**

Thanks !

**Comment by m1t0z** [comment]
Hi, @antoinemadec.

I can confirm that after updating the `coc-fzf` plugin it starts to account `list.source.symbols.excludes` and now the behavior of the `:CocList symbols` and `:CocFzfList symbols` is similar.

Thank you very much!

p.s. from my perspective the issue could be closed.
