### ISSUE TITLE
How to change the open command on a coc_location command

### ISSUE THREAD

**Issue by Rofer11607** [antoinemadec/coc-fzf#112]
I have remmaped my files command to jump to a window if the file is already open, I like so:

:command -nargs=1 FileRef :call FileRefFunc("<args>")

function! FileRefFunc(path)
  echom a:path
      try
            :execute "sbuffer ".a:path
      catch
            :execute "edit ".a:path
      endtry
endfunction

command! -bang -nargs=? -complete=dir Files
    \ call fzf#run(fzf#wrap('files', fzf#vim#with_preview({ 'dir': <q-args>, 'sink': 'FileRef', 'source': 'rg --files --hidden' }), <bang>0))

I would like to do the same thing for when I am opening files using roc-references, however I cannot find the place where I can replace the 'sink' with my function for coc-references. Please help :O)

**Comment by antoinemadec** [comment]
@Rofer11607 sorry for the late answer !

Please look at

- the code here: https://github.com/antoinemadec/coc-fzf/blob/master/after/plugin/coc_fzf.vim#L14-L26
- CocLocationsChange in Coc.nvim help
