### ISSUE TITLE
Color for diagnostic type (Error, Hint, Warning) doesn't respect the severity

### ISSUE THREAD

**Issue by wustho** [antoinemadec/coc-fzf#117]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```: `--layout=reverse-list --inline-info --bind ctrl-f:preview-down,ctrl-b:preview-up,ctrl-u:preview-page-up,ctrl-d:preview-page-down`
  - ```bat --version```: `bat 0.18.1`
  - Are your vim plugins up-to-date?: Yes
  - ```(n)vim --version```: `NVIM v0.8.0-dev-1170-g63be76518`
```
(n)vim --version output
NVIM v0.8.0-dev-1170-g63be76518
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az397-79

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

# Describe the Bug
Severity color (Error, Hint, Warning) in `:CocFzfList diagnostics` both for current buf and workspace doesn't seem to respect the severity. All being rendered Red.
![Screenshot_20220930_141137](https://user-images.githubusercontent.com/43810055/193215018-1088e305-6f74-40fb-a153-62b98186b449.png)

# To Reproduce
No config done apart from layout `vim.g.coc_fzf_preview = 'up:50%'`

## Steps to Reproduce
Just run `:CocFzfList diagnostics`

# Expected Behavior
The color for severity message should respect the severity. eg. Error: red, Hint: blue, Warning: yellow.

Thanks for this great plugin btw.

**Comment by antoinemadec** [comment]
Could you please provide me with the minimal vimrc to reproduce that bug ?

**Comment by antoinemadec** [comment]
Please reopen with minimal vimrc if issue persists.

**Comment by jaburns** [comment]
https://github.com/antoinemadec/coc-fzf/issues/126#issuecomment-1357560633
haha sounds like you're probably not too excited about working on this anymore, and I don't care enough to do the work and open a PR, so I'll leave this context here for anyone who might discover it and want to fix it. I think I'll just also switch to telescope.

**Comment by antoinemadec** [comment]
The telescope plugin is doing what i need.
Moving forward, i think this is the way to go
