### ISSUE TITLE
Help needs for fzflist preview window 

### ISSUE THREAD

**Issue by zl03jsj** [antoinemadec/coc-fzf#122]
needs some help..
the color in 'background=dark' looks good, once change to  'light' the color looks weird
![image](https://user-images.githubusercontent.com/10127848/196353032-81952917-4bcd-4e68-9afd-ef957a0a4f77.png)

**Comment by antoinemadec** [comment]
@zl03jsj there is a template for bug reports for a reason.

Please provide the **minimal** vimrc and steps to reproduce.
This ticket will be closed in a week from now otherwise. Thanks.

**Comment by antoinemadec** [comment]
@zl03jsj could you please provide a **minimal** vimrc instead of whole config file ?
My guess is that the issue lies with the colorscheme you are using.

**Comment by zl03jsj** [comment]
> @zl03jsj could you please provide a **minimal** vimrc instead of whole config file ? My guess is that the issue lies with the colorscheme you are using.

ok, i will do some research on this.
