### ISSUE TITLE
cocfzflist border is broken.

### ISSUE THREAD

**Issue by zl03jsj** [antoinemadec/coc-fzf#129]
the border of cocfzflist window border is broken, how can i fix this:
<img width="747" alt="image" src="https://github.com/antoinemadec/coc-fzf/assets/10127848/51db534d-2cc9-42c3-85e6-fcb8cddf3bb9">

options:
```lua
vim.g.fzf_preview_window = {'up,65%', "ctrl-/"}
vim.g.fzf_layout = { window={ width=0.8, height=0.7 } }
```

**Comment by antoinemadec** [comment]
Please feel this template first

# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
  - ```bat --version```:
  - Are your vim plugins up-to-date?:
  - ```(n)vim --version```:
```
(n)vim --version output
```

# Describe the Bug
A clear and concise description of what the bug is.
You can also include screenshots if needed.

# To Reproduce
## **Minimal** vimrc
```vim
" minimal vimrc
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. ```:e myfile.py```
3. etc

# Expected Behavior
A clear and concise description of what you expected to happen.

**Comment by zl03jsj** [comment]
configuration of coc-fzf:
```lua
local M = {
    'antoinemadec/coc-fzf',
    branch = 'master',
    lazy = false,
    dependencies = {
        { 'junegunn/fzf',     branch = "master", build = "./install --all" },
        { 'junegunn/fzf.vim', branch = 'master' },
    },
    config = function()
        vim.fn['coc_fzf#common#add_list_source']('fzf-buffers', 'display fzf buffers', 'Buffers')
        vim.cmd([[
        let g:fzf_layout = { 'window': { 'width': 0.80, 'height': 0.85 } }
        ]])
    end,
    keys = {
        { "<leader>ss", "<cmd>CocFzfList symbols<cr>" },
        { "<leader>o",  "<cmd>CocFzfList outline<cr>" },
    },

}

return M
```
- echo $FZF_DEFAULT_OPTS
--nothing---
- bat --version
bat 0.23.0
- nvim --version
```shell
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```
-

**Comment by zl03jsj** [comment]
and another question, command: `CocFzfList extensions`, doesn't pop up in floating window:
<img width="519" alt="image" src="https://github.com/antoinemadec/coc-fzf/assets/10127848/49b600a8-70be-43b5-8f6f-7f63338dad72">

**Comment by zl03jsj** [comment]
maybe this problem only occurs on neovim.
because, it haven't happen until i used neovim.

**Comment by zl03jsj** [comment]
since there are no new messages for a long time, close this issue.
