### ISSUE TITLE
coc-fzf/script/get_workspace_symbols.py unexpectedly requires pynvim

### ISSUE THREAD

**Issue by Ozaq** [antoinemadec/coc-fzf#131]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```: ""
  - ```bat --version```: N/A
  - Are your vim plugins up-to-date?: Yes
  - ```(n)vim --version```:

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

# Describe the Bug

Running ":CocFzfList symbols" reports that get_workspace_symbols.py could not be executed successfully, unfortunately the output of the command is cut off. But the full command can be pasted, this reveals that `pynvim` is missing:

```
python3 /Users/ozaq/.config/nvim/plugged/coc-fzf/script/get_workspace_symbols.py  /var/folders/68/h1h7hy7n4bq5w69q7qdrrtvc0000gn/T/nvim.ozaq/HyN2TH/nvim.28789.0 4
Traceback (most recent call last):
  File "/Users/ozaq/.config/nvim/plugged/coc-fzf/script/get_workspace_symbols.py", line 7, in <module>
    from pynvim import attach
ModuleNotFoundError: No module named 'pynvim'
```

# To Reproduce
Clean install of nvim and Plug with config from this README. Have some symbol server setup, e.g. clangd and use `:CocFzfList symbols`

# Expected Behavior

Ideally no error :)  

However since you are executing python script and this is using any potentially active virtual environment I think a ok solution would be to add this to requirements in the README or add a hint to the error output, e.g. "Could not run get_workspace_symbols.py! Do you have pynvim installed?"

**Comment by antoinemadec** [comment]
@Ozaq makes sense, could you please create a PR adding the pynvim requirement?

**Comment by Ozaq** [comment]
will do!
