### ISSUE TITLE
Support Preview for diagnostic list

### ISSUE THREAD

**Issue by expipiplus1** [antoinemadec/coc-fzf#15]
The preview for the `locations` list is awesome, it would be super if one could toggle a preview for diagnostic messages too. I had in mind the preview showing the full diagnostic message with line breaks and all, but I suppose also previewing the location would be nice to have too.

**Comment by antoinemadec** [comment]
@expipiplus1 , this is not the default behavior of ```:CocList diagnostics```.

I could maybe add a key to toggle the preview, like ```?``` for instance.
But preview would be off by default to match ```:CocList diagnostics``` behavior.

Would that be OK for you?

**Comment by antoinemadec** [comment]
@expipiplus1 , I take that back.
The preview is so awesome I decided to make it the default :smile: 

If someone is bothered by that behavior, we can still add an option later on.

**Comment by wookayin** [comment]
Great feature! Could we make preview key configurable as well?

**Comment by antoinemadec** [comment]
@wookayin , I don't think I will, but PR are welcome :smile:

**Comment by antoinemadec** [comment]
@wookayin , I broke under peer pressure: https://github.com/antoinemadec/coc-fzf/commit/23c2c56c3c86aa7bb076c21bd27c27512c62e9f7

**Comment by wookayin** [comment]
@antoinemadec, I was meaning no pressure, but yeah, that's awesome. Thanks!

**Comment by antoinemadec** [comment]
@wookayin , oh no worries, I was just kidding :smile: (will need to use a smiley next time)

**Comment by expipiplus1** [comment]
Wow, thanks!

I mean no pressure by the issues too, only opening them for completeness
sake!

**Comment by baipaiha** [comment]
great feature, great plugin, thx
Automatic preview for "CocFzfList symbols" would be awesome !

by the way, i'm not able to launch preview by pressing '?' since it's interpreted as a seach pattern. is there an escape code ? or this feature is not available for symbols list ?

**Comment by antoinemadec** [comment]
@baipaiha thanks!
Previews are not available for symbols for now.
PR welcome🙂

Antoine

**Comment by antoinemadec** [comment]
@baipaiha preview on symbols was added by https://github.com/antoinemadec/coc-fzf/commit/ba8cf9afc8aae3ea4086d89a01bd414d42a6b8bc

**Comment by baipaiha** [comment]
great ! thx !
