### ISSUE TITLE
Initially display list in MRU order

### ISSUE THREAD

**Issue by expipiplus1** [antoinemadec/coc-fzf#16]
... or at least with the last used element at the top.

`CocList` seems to do this, keeping the previously selected element under the cursor when opening a list again, it's quite handy.

**Comment by antoinemadec** [comment]
Nice idea, but not a priority for now.
PR is welcome :smiley:

**Comment by antoinemadec** [comment]
> ... or at least with the last used element at the top.

@expipiplus1 , wouldn't ```:CocFzfListResume``` fit the bill?

I actually really like the fact that the sources as sorted in an alphabetical order.
The MRU always confuses me on ```:CocList```...

**Comment by expipiplus1** [comment]
@antoinemadec perfect, thanks!
