### ISSUE TITLE
[Feature Request] CocList support

### ISSUE THREAD

**Issue by fgheng** [antoinemadec/coc-fzf#2]
Hello, your plugin is great, I like it very much. I have a new feature request, Is it possible to add `CocList` function, thank you.

**Comment by fgheng** [comment]
and support tags

**Comment by antoinemadec** [comment]
@fgheng thanks a lot :smiley: 
OK, so if I understand, you would like to add the equivalent of:

1. ```:CocList``` : basically a menu presenting all the available sources
2. ```:CocList tags``` : is this coming from https://github.com/neoclide/coc-lists ?
3. ```:CocList functions``` : I did not find this in any Coc plugin

Regarding 1., I don't really use this in Coc anyway. I prefer mapping the list I use directly.
Would you be interested creating a PR for that?

Regarding 2., [fzf.vim](https://github.com/junegunn/fzf.vim) already has the ```:Tags``` command. Is there any advantage to use ```:CocList tags```?

Regarding 3., this sounds great. Could you please point to the plugin so I can install/check it?

Thanks,
Antoine

**Comment by fgheng** [comment]
thank you very much.
I may be mistaken about functions, there really are no CocList functions.
1. My technical ability is limited about vim, hahah...
2. fzf.vim`: Tags `show less information than `CocList tags`.
3. I do not find the relevant plugs, but I thought of it from [vista](https://github.com/liuchengxu/vista.vim)

**Comment by antoinemadec** [comment]
1. got it, no problem. I might add this later, but I don't guarantee anything as I never use ```:CocList``` without the name of the list that interest me
2. I tried ```CocList tags``` and I did not see more information compared to ```:Tags``` (except for nicer highlighting). Could you please give me an example of when more info is provided by ```CocList tags```?
3. Sorry but ```coc-fzf``` aims to use fzf for ```CocList``` sources when possible. I won't add functionalities from plugin besides coc.

**Comment by antoinemadec** [comment]
Regarding 2., I must admit after using it a bit longer, ```:CocList tags``` is nicer looking and clearer than ```:Tags```.
I just open an [issue](https://github.com/neoclide/coc-lists/issues/75) to ask for a feature that is needed if we want to implement ```:CocList tags``` in coc-fzf.

**Comment by fgheng** [comment]
ok, thank you very much

**Comment by antoinemadec** [comment]
@fgheng , the maintainer of ```coc-lists``` told me to stick with ```:Tags```, I think this makes sense.
```:CocList tags``` does not have more info anyway, just better highlighting.

So out of the 3 requests, only ```:CocList``` makes sense now.
As previously said, I don't use it myself, so I am not sure I will implement it.
PRs are welcome :smiley:

**Comment by fgheng** [comment]
Thank you anyway :smile:

**Comment by antoinemadec** [comment]
@fgheng ```:CocList``` support has been added in this commit: a8c05c9ee2bf92dd4358f19c6cfc95f1f5241e3d
:wink:

**Comment by wookayin** [comment]
I've left some feedback on a8c05c9.

**Comment by antoinemadec** [comment]
@wookayin , let's keep on talking on #3
