### ISSUE TITLE
"CocFzfList symbols" takes you to the end of a function's body, not the beginning

### ISSUE THREAD

**Issue by sethfowler** [antoinemadec/coc-fzf#20]
This is a great plugin! I've hit one snag: if I run `CocList -I symbols` and select a function, I'm taken to the beginning of the function definition, which is where I want to go. `CocFzfList symbols` takes me to the end of the function body instead. This seems like a bug, although maybe there's just a configuration option I don't know about. I'm testing with TypeScript code using `coc-tsserver`, in case that's helpful.

**Comment by antoinemadec** [comment]
Could you please give me a minimal file example to reproduce this?

**Comment by sethfowler** [comment]
@antoinemadec Would a non-minimal example work? 🙂 [This repo](https://github.com/sethfowler/chromium-trace-analyzer) demonstrates the problem. These steps should work:
1. Clone the repo.
2. Run `npm install`.
3. Run `nvim src/index.ts`.
4. Run `:CocFzfList symbols`.
5. Start typing `applySourceMapToAttributions` until it shows up, and then select it from the list.
6. You'll end up with the cursor at the end of the function rather than the beginning.

I'd be happy to construct a more minimal example if it's too hard to debug using this one.

**Comment by antoinemadec** [comment]
A minimal example would be easier to debug, thanks.

**Comment by sethfowler** [comment]
@antoinemadec I tracked down the issue; the fix is in #22.
