### ISSUE TITLE
:CocFzfList symbols fails

### ISSUE THREAD

**Issue by romariolopezc** [antoinemadec/coc-fzf#23]
![image](https://user-images.githubusercontent.com/6199588/78456110-0c62e580-765f-11ea-9e45-3b0b613360cb.png)

The command I used with coc was: `:CocList -I symbols`

**Comment by antoinemadec** [comment]
@romariolopezc , seems to be a python 3.8 new warning: https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

Weirdly enough, I use python 3.8.2 and don't see this warning, but I fixed the issue reported by this SyntaxWarning here: https://github.com/antoinemadec/coc-fzf/commit/122e4c224fed159ed4d11164f73a4bbe6a96c08b

Could you please update `coc-fzf` and try again?

**Comment by romariolopezc** [comment]
Updated and now is working, thank you!
