### ISSUE TITLE
Using coc-definition outputs a command

### ISSUE THREAD

**Issue by romariolopezc** [antoinemadec/coc-fzf#25]
When using:
```
nmap <silent> gd <Plug>(coc-definition)
```

When the definition is oppened from a different file, this outputs instead of the file name:
![image](https://user-images.githubusercontent.com/6199588/78458310-9c0f9080-766d-11ea-9422-7400b9d40121.png)

**Comment by romariolopezc** [comment]
Going to different buffers with `:bnext` outputs something similar in the file name:
![image](https://user-images.githubusercontent.com/6199588/78458481-e6ddd800-766e-11ea-96c9-e80111d6b833.png)

**Comment by antoinemadec** [comment]
Could you provide a minimal testcase, with:
- minimal vimrc
- minimal set of files
- exact steps to reproduce the issue

Thanks in advance :grinning:

**Comment by antoinemadec** [comment]
@romariolopezc , any news about this?

**Comment by romariolopezc** [comment]
I'm not sure if is caused by this plugin or another updated plugin :cry: 

Feel free to close it

**Comment by antoinemadec** [comment]
@romariolopezc , no problem :smiley: 
Please reopen if you see that this was in fact due to coc-fzf.
