### ISSUE TITLE
Plugin should use python interpreter set on nvim(python3_host_prog)

### ISSUE THREAD

**Issue by felippemr** [antoinemadec/coc-fzf#26]
First, thanks for this!

I installed the plugin but it seems to be using the python interpreter for the current virtualenv I am in as opposed to using the python interpreter I set on `python3_host_prog`(on neovim).

I installed the python `neovim` module on the interpreter set by `python3_host_prog`.

Also checked `get_workspace_symbols` and saw `#!/usr/bin/env python3`.

**Comment by felippemr** [comment]
Example of how deoplete uses it https://github.com/Shougo/deoplete.nvim/blob/ea28dd49b78c30c64ef8eb03de5307a6eb98048b/autoload/deoplete/init.vim#L41

**Comment by felippemr** [comment]
I have zero experience with vim script but I tried implementing it! Let me know if it makes sense.

**Comment by felippemr** [comment]
I didn't know how to test locally so I don't even know if this works.

**Comment by antoinemadec** [comment]
@felippemr , thanks for reporting this :smiley: 

I have a crazy work schedule rn, and I'm about to be a daddy, so don't expect me to be super reactive...
I will take a look at your PR as soon as possible, however you might have to fix it yourself.

Thanks again!

**Comment by felippemr** [comment]
Congratulations! I will fix it if needed , no worries. Can you tell me how can I test it locally as well?
