### ISSUE TITLE
Installation impossible with :CocInstall coc-fzf

### ISSUE THREAD

**Issue by emmtte** [antoinemadec/coc-fzf#28]
when used

````:CocInstall coc-fzf````
I have this error message
````
[coc.nvim] Error on install coc-fzf: Error: Invalid response from https://registry.npmjs.org/coc-fzf: 404
````

**Comment by Avi-D-coder** [comment]
Use your vim plugin manager.
`Plug 'antoinemadec/coc-fzf'`

**Comment by antoinemadec** [comment]
@emmtte , as @Avi-D-coder said, for non-official Coc plugins, you have to install it like any other vim plugin: ```Plug  'antoinemadec/coc-fzf'```

However, I just opened an issue to the maintainer of Coc Marketplace to see if they would be open to adding coc-fzf.

I will keep this issue open until I get a clear answer from them.

**Comment by fannheyward** [comment]
I don't think you can do `CocInstall coc-fzf`, because `coc-fzf` is not a node package. `CocInstall` just do npm/yarn install, ([code](https://github.com/neoclide/coc.nvim/blob/master/src/model/extension.ts#L126)) , the better way to install is using vim plugin manager, like `vim-plug`.

**Comment by antoinemadec** [comment]
@fannheyward , thanks a lot for the clear reply :smiley:
