### ISSUE TITLE
fork/exec...invalid argument in preview window in diagnostic list

### ISSUE THREAD

**Issue by expipiplus1** [antoinemadec/coc-fzf#29]
When I use the preview window in the diagnostic window I just see the error message

```
fork/exec /nix/store/jirzjbbpl4j2kl2f01cfnrralxr5aw7a-bash-interactive-4.4-p23/bin/bash: invalid argument
```

There are a couple of `messages` but no smoking gun 

```
"term://.//27510:( /nix/store/47xbab83hlcgslkxd3scmfvvj4axfsw7-vimplugin-coc-fzf-2020-03-06/share/vim-plugins/coc-fzf/script/get_lists.sh )|'fzf'  '--multi' '--expect=ctrl-v,ctrl-x,ctrl-t' '--ansi' '--prompt=Coc Lists> ' '--layout=reve
rse-list' --no-height > /run/user/1000/nvimaRXPaQ/5;#FZF" line 25 of 25 --100%-- col 14
"term://.//27546:cat '/run/user/1000/nvimaRXPaQ/7'|'fzf'  '--multi' '--expect=ctrl-v,ctrl-x,ctrl-t' '--ansi' '--prompt=Coc Diagnostics> ' '--layout=reverse-list' '--preview-window' 'up:50%' '--preview' ''\''/nix/store/x4dq0vy0mcfqrnhx2
pn48411k5bk67py-vimplugin-fzf-vim-2020-01-14/share/vim-plugins/fzf-vim/bin/preview.sh'\'' {}' '--bind' '?:toggle-preview' --no-height > /run/user/1000/nvimaRXPaQ/6;#FZF" line 25 of 25 --100%-- col 1
```

I am using the latest coc-fzf and fzf-vim

**Comment by antoinemadec** [comment]
@expipiplus1 , I am also using the latest coc-fzf and fzf-vim and I cannot reproduce this.

Could you please share:

- the **minimal** vimrc to reproduce this
- the exact commands/key strokes to type to reproduce this

Thanks!
Antoine

**Comment by expipiplus1** [comment]
Sorry for the somewhat lazy issue :)

Is there an easy way to fake lsp or coc output? This happens with the haskell ide engine which sadly isn't trivial to set up.

Just a guess, but do you think it could be to do with either quotes or newlines in the error message?

I just noticed that in my current buffer there are five error messages, and only the two messages with quotes and newlines show this message in the preview window.

If that doesn't ring any bells then I'm happy to close this issue until I can work up the courage to get a repro :)

**Comment by antoinemadec** [comment]
@expipiplus1 , so this issue is seen when using ```:CocFzfList diagnostics``` correct?
However, the error message you sent in your previous message was mentioning ```Coc List```, so I'm a little confused...

Please at least send me:

- commands you are typing
- the diagnostic message that seems to be the issue

If I have those, I could at least try to understand where the problem might be and maybe hack the plugin to reproduce the error.

**Comment by expipiplus1** [comment]
@antoinemadec 

The command is `CocFzfList diagnostics`

The diagnostic message is:

```
[bios] [E] Could not load module ‘Data.Text’
It is a member of the hidden package ‘text-1.2.4.0’.
Perhaps you need to add ‘text’ to the build-depends in your .cabal file.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

And it appears at `utils/Control/Monad/Trans/Resource/Local.hs:10:1`

Thanks :)

**Comment by antoinemadec** [comment]
@expipiplus1 , thanks a lot!

The issue was with FZF (or fzf.vim), where multi-line strings were not handled properly.
I just substituted every ```"\n"``` for ```" "``` in the diagnostic message.

Thanks again,
Antoine

**Comment by expipiplus1** [comment]
Thanks!
