### ISSUE TITLE
Use :CocFzfList {source} instead of :CocFzfListSource

### ISSUE THREAD

**Issue by wookayin** [antoinemadec/coc-fzf#3]
Hi,

- `:CocFzfListCommands` are a counterpart of `:CocList commands` and
- `:CocFzfListDiagnostics` are of `:CocList diagnostics`, etc.

I personally these command names are quite verbose and cannot type them easily. Why not `:CocFzf {commands, diagnostics}`, etc.? One can use their own command aliases or mappings, but wanted to see if it is something you may want to support officially.

**Comment by antoinemadec** [comment]
@wookayin , I want to keep ```CocFzfList``` in the name. I think ```CocFzf``` is not enough as you could use Fzf with Coc for other things than only list.

However, ```:CocFzfList {commands, diagnostics}``` sounds like a good idea, especially if we enable completion for the source name.

Would you be interested in implementing it?
As a side note, I am currently implementing ```:CocFzfList``` to display all available sources.

Thanks,
Antoine

**Comment by wookayin** [comment]
`:CocFzfList <list-type> [args...]` sounds good to me -- will try on my free cycle. `:CocFzfList` (akin to `:CocList`) would be also great!

**Comment by antoinemadec** [comment]
@wookayin , just added ```:CocFzfList``` in a8c05c9ee2bf92dd4358f19c6cfc95f1f5241e3d
Any feedback is welcome :smile:

**Comment by antoinemadec** [comment]
b95ea3bcffe67c0f4e0e90a161790d2608a0e99e fixes the script getting the comments for each list.
Please let me know when your ```:CocFzfList {source}``` PR is ready.

Thanks again for the feedback :+1:

**Comment by antoinemadec** [comment]
@wookayin , I just implemented this feature on the **issue_3** branch: https://github.com/antoinemadec/coc-fzf/tree/issue_3

Could you please test it and modify it if needed?

Thanks!
Antoine

**Comment by wookayin** [comment]
To ease our discussion and review through the [Github workflow](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews), could we make a pull request for `issue_3`?  Thanks!

**Comment by antoinemadec** [comment]
@wookayin we can :smile:

**Comment by antoinemadec** [comment]
Implemented in https://github.com/antoinemadec/coc-fzf/commit/1143dad4c49474905669ec54708270f08fc38669

**Comment by wadkar** [comment]
For the sake of posterity and to the benefit of our search overlords:

If you are getting`E492: Not an editor command: CocFzfListCommands` in your neovim because you set some keymaps ([prior to this change](https://github.com/antoinemadec/coc-fzf/commit/1143dad4c49474905669ec54708270f08fc38669#)) and they are no longer working.

Please update your keymaps by carefully observing the space. We now have one "common" `CocFzfList` command which takes arguments now.

**Comment by antoinemadec** [comment]
@wadkar we are trying to mimic coc.nvim behavior, they have 2 functions CocList and CocListResume.

Thanks,
Antoine
