### ISSUE TITLE
Issue with neoterm

### ISSUE THREAD

**Issue by felippemr** [antoinemadec/coc-fzf#31]
For some reason [`coc-fzf#common#fzf_selector_save` ](https://github.com/antoinemadec/coc-fzf/blob/5bf230e38054d927305b6ac5a5e9158301ba28c3/autoload/coc_fzf/common.vim#L17)sometimes is being called when I am in neoterm. I don't understand why but it only happens sometimes and only stops after I restart neovim.

![Screen Shot 2020-04-27 at 12 17 22 PM](https://user-images.githubusercontent.com/2388162/80411431-0ee0e580-8881-11ea-91df-5e39cb36d641.png)

The only key that errors is the `<CR>`, enter in my case.

**Comment by antoinemadec** [comment]
Hi @felippemr , ```fzf_selector_save``` is called through the following autocmd:
```vim
autocmd TermEnter  * if &ft == 'fzf' | call coc_fzf#common#remap_enter() | endif
```
Is ```neoterm```'s ft=fzf?
If that's the case, it might be better to use a buffer variable to trigger ```remap_enter()```.

**Comment by felippemr** [comment]
Hey @antoinemadec , thanks for the quick response.
> Is neoterm's ft=fzf?

How can I check?

**Comment by antoinemadec** [comment]
First, go to normal mode in your term with: ```<c-\><c-n>```
Then, do: ```:echo &ft```

**Comment by felippemr** [comment]
The response was `neoterm`. I will do it again when it fails to see if it changes.

**Comment by antoinemadec** [comment]
OK, please also provide a **minimal** ```vimrc``` as well as precise instructions to reproduce the error.

**Comment by felippemr** [comment]
```
let g:plugged_home = '~/.vim/plugged'

" Plugins List
call plug#begin(g:plugged_home)
  Plug 'kassio/neoterm'
  Plug 'antoinemadec/coc-fzf'
call plug#end()
filetype plugin indent on

nnoremap <silent> <space>a  :<C-u>CocFzfList diagnostics<CR>
nnoremap <silent> <space>b  :<C-u>CocFzfList diagnostics --current-buf<CR>
nnoremap <silent> <space>c  :<C-u>CocFzfList commands<CR>
nnoremap <silent> <space>e  :<C-u>CocFzfList extensions<CR>
nnoremap <silent> <space>l  :<C-u>CocFzfList location<CR>
nnoremap <silent> <space>o  :<C-u>CocFzfList outline<CR>
nnoremap <silent> <space>s  :<C-u>CocFzfList symbols<CR>
nnoremap <silent> <space>S  :<C-u>CocFzfList services<CR>
nnoremap <silent> <space>p  :<C-u>CocFzfListResume<CR>

tnoremap <Esc><Esc> <C-\><C-n>

set shell=bash\ -l
```
This is my `init.vim`.

To replicate:

-  install the plug dependencies
-  open a new nvim instance
-  go to normal mode and then start as new neoterm(`:Tnew`)
-  try to press enter

Sometimes the error happen, sometimes it does not and I haven't figured it out why.

**Comment by felippemr** [comment]
The workaround it, for now, is to close all the opened neoterm sessions and open new ones.

**Comment by antoinemadec** [comment]
@felippemr , I tried to reproduce you steps 10 times and never saw any issue on my end.
Questions:

1. is ```echo &ft``` equals to neoterm also when it fails?
2. what is your neovim version?
3. does the bug happens only happens if you opened a FZF buffer before?

If 3. is the case please send me a new vimrc and new instructions to include this in your testcase.

**Comment by felippemr** [comment]
Hey @antoinemadec , thanks for being so helpful and responsive!

> is echo &ft equals to neoterm also when it fails?

Yes

> what is your neovim version?

0.4.3

> does the bug happens only happens if you opened a FZF buffer before?

I tried it sometimes and couldn't replicate it yet. It happens throughout my day and I haven't been able to recognize the pattern yet.

I will keep trying to replicate it and will post it here when I find something.

**Comment by antoinemadec** [comment]
@felippemr , please update and try again. I am pretty confident this should fix your issue :smiley: 
Don't hesitate to re-open if the issue persists. Cheers!
