### ISSUE TITLE
CocFzfList symbols not working

### ISSUE THREAD

**Issue by MarinPostma** [antoinemadec/coc-fzf#32]
hello!

when running `:CocFzfList symbols` and start writing a query, I get the following error:
```
[Command failed: python3 /home/mpostma/.config/nvim/plugged/coc-fzf/script/get_workspace_symbols.py  /tmp/nvimUXWUTd/0 3 3 'f']
```

Any idea how to fix this ?

**Comment by antoinemadec** [comment]
What happens is you try this command in a terminal?

Please keep in mind that the arguments of this command (<socket> <channel> <bufnr>) are different for each session.
Just try to run ```:CocFzfList symbols``` in your current session, and copy paste the command of the error message. Paste and execute it in a terminal.

Cheers,
Antoine

**Comment by MarinPostma** [comment]
Thank you Antoine! 
the error message pointed me to `pynvim`,which I hadn't re-installed with my latest installation, it now works like a charm :)

**Comment by antoinemadec** [comment]
Super, ravi de pouvoir aider :smiley:
