### ISSUE TITLE
Using :CocFzfList outline doesn't store jumps

### ISSUE THREAD

**Issue by romariolopezc** [antoinemadec/coc-fzf#33]
Hello! First, thanks for this package, is awesome

When using `CocFzfList outline` and going to a definition, I can jump back but not forward, I think when going to the definition the jumps is not stored?

I tested with `CocList outline` and the behaviour is correct, jumping back and forth after selecting an option

EDIT: I wanted to take a GIF for demonstration and did `:clearjumps` and while I was testing, I saw that there are no jumps being stored, so can't go back or forward, which is not the case for just using `:CocList outline`

**Comment by antoinemadec** [comment]
@romariolopezc , thanks a lot for reporting.
You are right, this is impacting: diagnostics, location, outline and symbols.

This is because I am using ```cursor()``` to go the the desired line, and it does not store it in the jumplist.
I will work on a solution today or tomorrow.

Antoine

**Comment by romariolopezc** [comment]
Thank you!

How do you store it in the jumplist? I want to learn to be able to help on the future

**Comment by antoinemadec** [comment]
@romariolopezc , you can use ```m'``` to add the current position in the jumplist.
Per Vim help, it "Set the previous context mark.".

Feel free to look at the commit and ask me any question on the code if you plan on contributing :smiley: 

Thanks again for reporting :heart: ,
Antoine
