### ISSUE TITLE
CocFzfList symbols notworking

### ISSUE THREAD

**Issue by samhvw8** [antoinemadec/coc-fzf#35]
Hi @antoinemadec 
when i run command :CocFzfList symbols i got error

![image](https://user-images.githubusercontent.com/12538214/82522040-702f6800-9b52-11ea-9800-fdd561817984.png)

```bash

/Users/samhv/.config/nvim/plugged/coc-fzf/script/get_workspace_symbols.py /var/folders/7p/xqgf0dgs61q2c7g61bs3dc500000gn/T/nvimW3zUBj/0 3 4 'a'
Traceback (most recent call last):
  File "/Users/samhv/.config/nvim/plugged/coc-fzf/script/get_workspace_symbols.py", line 52, in <module>
    'getWorkspaceSymbols', args.query, int(args.bufnr))
  File "/Users/samhv/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/Users/samhv/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/samhv/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:Error invoking 'CocAction' on channel 3 (coc):
Method "CocAction" not exists with coc.nvim

```

For Version
```
vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78
term: iTerm.app
platform: darwin
Python version: 3.7.7
pynvim version: 0.4.1

```

please help :(

**Comment by antoinemadec** [comment]
@samhvw8 you are right , after updating Coc.nvim I get the same error message, I will work on this.

Thanks,
Antoine

**Comment by antoinemadec** [comment]
@samhvw8 , it appears the maintainer of coc.nvim is changing its API and what is accessible to other plugin like coc-fzf: https://github.com/neoclide/coc.nvim/issues/1937

If we cannot have access to Coc's lists and symbols, I am afraid that this means the end of ```coc-fzf``` :cry:

**Comment by chemzqm** [comment]
The bug on master branch was fixed by https://github.com/neoclide/coc.nvim/pull/1987

**Comment by antoinemadec** [comment]
@samhvw8 , this fixes the issue with symbols.
Thanks for reporting this issue :smiley:

**Comment by samhvw8** [comment]
@chemzqm  @antoinemadec  Thanks you for fix the issues 🎉
