### ISSUE TITLE
yank: add block/line/char info

### ISSUE THREAD

**Issue by antoinemadec** [antoinemadec/coc-fzf#36]
Hi @asermax ,

Could you please also add the block/line/char info in ```CocFzfList yank``` in order to match ```CocList yank```?

You can get the info from the yank file:

- |V| is line
- |v| is char
- |^v| is block

Do not hesitate to ask me any question :smiley: 

Thanks,
Antoine

**Comment by asermax** [comment]
Sure, now that the basic functionality is in place (which is what I use the most), I was thinking on adding those extras as well.
Will do when I have some free time 👍

**Comment by timtyrrell** [comment]
Preview would be amazing, also. 🙏  Either way, thanks for getting Yank it there, I appreciate it.

**Comment by antoinemadec** [comment]
Preview for yank list is possible in theory, it will require to pass ```<file>:<line_nb>``` at the end of each line in FZF.
Since we don't want the user to see those info at the end of each FZF line, we could highlight it with the ```Ignore``` highlight group.
Similar things have been done in  ```autoload/coc_fzf/symbols``` for instance.

That being said, this would not work perfectly on **char** and **block** yanks as ```fzf.vim``` preview script only highlights 1 whole line at a time.
It would still be a good indication of where the yank pattern is coming from.

**Comment by asermax** [comment]
I'll start playing with this now that my other PR got merged, sorry for the delay!

**Comment by antoinemadec** [comment]
@timtyrrell , preview was added.
Please update and let us know if you encounter any issues :wink:

**Comment by timtyrrell** [comment]
@antoinemadec I saw that and already updated! I looks pretty slick so far, thanks a lot!
