### ISSUE TITLE
[Feature Request] Do you plan to support the fzf.vim command?

### ISSUE THREAD

**Issue by yutakatay** [antoinemadec/coc-fzf#45]
I would like to use coc-fzf as the only interface to fzf.
Do you plan to support fzf.vim's `:Files` , `:Buffers` and other commands?
https://github.com/junegunn/fzf.vim#commands

In short, it means adding a `:CocFzfList files`, `:CocFzfList buffers`  command or something like that.

**Comment by antoinemadec** [comment]
Hi @yutakatay , the goal of ```coc-fzf``` is to use Fzf to manipulate CocList sources (like diagnostics etc).

```:Files``` and ```:Buffers``` commands are already defined by ```fzf.vim``` and I don't plan to make ```:CocFzfList``` a wrapper for those commands. It would make things very confusing.

I personally never type those commands manually as I prefer to use keyboard mappings.
 
However, you could implement a command of your own that would wrap all your Fzf commands.
Here is an example adding ```:Files``` and CocFzf list in a wrapper ```:MyFzf```:
```vim
command! -nargs=* -complete=custom,MyFzfComplete MyFzf call MyFzf(<f-args>)

function MyFzfComplete(ArgLead, CmdLine, CursorPos)
  let coc_opts =  coc_fzf#common#list_options(a:ArgLead, a:CmdLine, a:CursorPos)
  let CmdLineList = split(a:CmdLine)
  let source = len(l:CmdLineList) >= 2 ? l:CmdLineList[1] : ''
  if empty(source)
    return "files\n" . coc_opts
  elseif source == "files"
    return ""
  else
    return coc_opts
  endif
endfunction

function MyFzf(...)
  let source = a:0 ? a:1 : ''
  if source == 'files'
    :Files
  else
    exe "CocFzfList " . join(a:000, ' ')
  endif
endfunction
```

Another option would be to create a Fzf window listing all the Fzf commands.
If you want to do this, take a look at ```coc-fzf/autoload/coc_fzf/lists.vim```.

I hope this helps!
Antoine

**Comment by yutakatay** [comment]
I'll try it. Thank you :smile:

**Comment by antoinemadec** [comment]
@yutakatay , I created a **release** branch to match coc.nvim's release branch.
You can know use the following in your vimrc in order not to have coc.nvim and coc-fzf in sync:
```vim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'antoinemadec/coc-fzf', {'branch': 'release'}
```

This will avoid keeping coc-fzf to the right revision manually :smile:

**Comment by antoinemadec** [comment]
@yutakatay , the needed PR has been pushed on Coc's release branch, I also updated Coc-Fzf's release branch.
**Could you please update your plugins and try the following function?**
```vim
call coc_fzf#common#add_list_source('fzf-buffers', 'display open buffers', 'Buffers')
```

Any feedback is welcome :smiley:

**Comment by yutakatay** [comment]
I just used it and it worked fine. I'll try to use it some more.

Thank you :wink:
