### ISSUE TITLE
I'd like to refer to the coc-fzf implementation

### ISSUE THREAD

**Issue by yuki-ycino** [antoinemadec/coc-fzf#46]
I'm a developer of [fzf-preview.vim](https://github.com/yuki-ycino/fzf-preview.vim/).
I've recently been working on coc extensions as coc-fzf-preview.
I'm implementing Diagnostics and References for coc, can I refer to the coc-fzf syntax highlight?

If it's OK, I'd like to implement it and then link to the README.

**Comment by antoinemadec** [comment]
@yuki-ycino , absoluetly, no problem.
This is free software, you can definitely reuse whatever code you want :smiley: 

Closing the issue for now, but feel free to ask me any question you might have.

Cheers,
Antoine

**Comment by yuki-ycino** [comment]
Thank you!
Implemented and described in the README.
