### ISSUE TITLE
Color is wrong?

### ISSUE THREAD

**Issue by lkhphuc** [antoinemadec/coc-fzf#47]
![Screenshot 2020-07-27 at 16 38 03](https://user-images.githubusercontent.com/12573521/88561613-8c0a2b00-d027-11ea-8e44-42c686c4e262.png)
Hello, first thank you for the plugin.
The above is the current color of my Coc-Fzf list, there is no distinction between the first word and the rest. All words has the color of the code comments.

Does anyone know a possible reason for this and a quick fix? Thanks in advance.

**Comment by antoinemadec** [comment]
@lkhphuc , thanks a lot for reporting this.
The first word is supposed to be highlighted, here is how it looks like for me:
![coc_list](https://user-images.githubusercontent.com/10830594/88563658-14b4a700-cfe7-11ea-981a-af9198197d1d.png)

That being said, the patterns used for the highlight might not be very robust.
**Could you please provide the minimal vimrc to reproduce this error?**

Thanks,
Antoine

**Comment by antoinemadec** [comment]
It might be coming from the relative numbers you have on your floating window.
Please provide the following info for me to reproduce:

1. **minimal vimrc**
2. vim/nvim version
3. are your plugins up-to-date?

Thanks!

**Comment by lkhphuc** [comment]
Thank for your help. I identified the culprit, a conflict with fzf-vim setting.
`let $FZF_DEFAULT_OPTS .= ' --border --margin=0,2'`
I deleted the above line and it's ok now, not sure why I had it in the first place.

**Comment by antoinemadec** [comment]
@lkhphuc nice!
Yes, those OPTS appear to create a box inside a box kind of window.
This messes up the highlight patterns.
