### ISSUE TITLE
Help with CocFzfList symbols

### ISSUE THREAD

**Issue by kyletruong** [antoinemadec/coc-fzf#48]
Is there a way to run `:CocFzfList symbols` over the current word my cursor is on? If there was functionality to do something like `CocFzfList symbols {mySymbol}` I could use `expand('cword')`. But it looks like I have to enter the floating modal first via `:CocFzfList symbols` then type the name of the symbol I'm searching.

**Comment by antoinemadec** [comment]
That's a sweet feature indeed, I am almost done implementing it.

Quick question, why do you want to query symbols matching the current word?
Just so you know, you can use ```gr``` to find references (```<Plug>(coc-references)```).

**Comment by antoinemadec** [comment]
@kyletruong please let me know if you face any issues after this commit.
Thanks!

**Comment by kyletruong** [comment]
I would love if `CocFzfList symbols` to work for the pop-up window and code preview. With `coc-references` the maintainer has commented that it wouldn't be easy to implement because of issues with the terminal buffer. [See here](https://github.com/neoclide/coc.nvim/issues/1586).

Thank you this is great! I'll try it out and let you know here if I experience any issues with it.

**Comment by antoinemadec** [comment]
All of the ```CocFzfList``` commands as well as the ```coc-references``` already work with  previews and floating windows.

Refer to the README, just make sure to have a proper installing in your **vimrc**, for instance:
```vim
Plug 'coc.nvim',
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf'
```

And then set add this in your **vimrc**:
```vim
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

And voila, ```CocFzfList symbols``` and ```<Plug>(coc-references)``` will now work in a Fzf popup window.
You can now use ```gr``` on a word and see all the references with previews and all.

Here is an example using ```gr``` on python function called ```load_pickle()```:
![gr_example](https://user-images.githubusercontent.com/10830594/89069160-7cd8f500-d327-11ea-8c9f-f1f3cd37813d.png)


Please let me know if this does not work for you.
