### ISSUE TITLE
Add support for "go to reference"

### ISSUE THREAD

**Issue by fgheng** [antoinemadec/coc-fzf#49]
just like [fzf-preview](https://github.com/yuki-ycino/fzf-preview.vim), it shows all reference in fzf float window

**Comment by antoinemadec** [comment]
It is already supported, just make sure to install fzf.vim, and to add the g:fzf_layout in yiur vimrc (see README).
Then gr will open references im a floating window with previews.

**Comment by antoinemadec** [comment]
Please confirm it fixed your issue, if not, please provide a minimal vimrc to reproduce the issue.

**Comment by fgheng** [comment]
Yes, it supports, thank you very much.
but there's a problem, it can not focus on the floated window when I use `gr` to open the reference window.

**Comment by fgheng** [comment]
Is that you rewrite <plug>(coc-references)? why I don't need to config something.

**Comment by antoinemadec** [comment]
For the focus issue, please provide the **minimal** vimrc to reproduce.

**Comment by antoinemadec** [comment]
For (coc-reference) i use the CocLocationsChange autocmd instrumented by Coc. See https://github.com/antoinemadec/coc-fzf/blob/master/after/plugin/coc_fzf.vim

**Comment by fgheng** [comment]
Sure, I know what happened.
When I used `gr` to open the floating window, it focused on the floating window, but not in insert mode, so when I use `ctrl j`(I map ctrl j to move the cursor to the down window) to move the item down, it moves to the window at the bottom.
How to set insert mode?

**Comment by antoinemadec** [comment]
It should already be in insert mode. Please provide minimal vimrc to reproduce.

**Comment by antoinemadec** [comment]
@fgheng , I tested the plugin with Vim, and I see the issue you are describing, as well as others.
I will open a new issue for that.

**Comment by antoinemadec** [comment]
Your problem seems to match 3- in that issue: #50 
I'm gonna close this issue for now, please keep an eye on #50

If you are using Neovim and not Vim, this could be another problem.
If that's the case feel free to re-open this issue :smiley:

**Comment by fgheng** [comment]
oh, I found what happened now. The keymap in my config file is wrong.

No matter what, thank you very much.
