### ISSUE TITLE
Vim issues

### ISSUE THREAD

**Issue by antoinemadec** [antoinemadec/coc-fzf#50]
This plugin does have issues with Vim:
1. no highlighting in Fzf window
2. <del>no highlighting in destination file when using ```gr``` (needs to do :e to re-trigger highlights)
3. <del>bug with floating window + ```gr``` where the floating window seems to be empty and then opens in a tab

Some of those issues might be related to other plugin (fzf, fzf.vim or coc.nvim).
**For now, the easy fix is to use Neovim instead of Vim :smile:**

**Comment by antoinemadec** [comment]
aeaf103fdef9f5f57d83d6ce6c76ec3bb871aaa6 and ca077f82959f34cb2859c6202736f00b747cd210 fixed 2- and 3-.

1- is actually a Vim issue where **syntax match** is not highlighted in **terminal** mode.

**Comment by antoinemadec** [comment]
@dianlujitao , you should now have beautiful colors in Vim as well.
Could you please update this plugin and confirm colors are working fine for you on Vim?

**Comment by dianlujitao** [comment]
Yay `:CocFzfList extensions` and `:CocFzfList commands` get colors now, thanks for the improvement!

**Comment by antoinemadec** [comment]
@dianlujitao , all CocoFzfList should now have colors now! If thats not the case, dont hesitate to open a new issue.
Thanks for confirming that its working 👍
