### ISSUE TITLE
g:coc_fzf_preview is invalid

### ISSUE THREAD

**Issue by fgheng** [antoinemadec/coc-fzf#57]
hello, I write `let g:coc_fzf_preview='up:50%'`, but the preview window is still in the right.

**Comment by antoinemadec** [comment]
Hi @fgheng , please provide a minimal **vimrc** to reproduce this issue.

Here is an example that works just fine with me:
```vim
call plug#begin('./plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf'
call plug#end()

let $FZF_DEFAULT_OPTS=''
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
let g:coc_fzf_preview = 'right:50%'
```

That being said, and as said in the README, if you want **coc-fzf** to behave like all your other Fzf programs, do the following:
```vim
let g:coc_fzf_preview = ''
let g:coc_fzf_opts = []
```

**Comment by antoinemadec** [comment]
Misread your issue, i thought you wanted to force it on the right. By default it should be up.
Once again, please provide minimal vimrc, and also provide the value of FZF_DEFAULT_OPTS.

**Comment by antoinemadec** [comment]
@fgheng , I was able to reproduce, I will fix it today.

**Comment by antoinemadec** [comment]
@fgheng , thanks for reporting the bug.
Please provide a minimal **vimrc** to reproduce next time, this would help me tremendously :wink:

**Comment by fgheng** [comment]
> @fgheng , thanks for reporting the bug.
> Please provide a minimal **vimrc** to reproduce next time, this would help me tremendously wink

ok, I see, next, I will.

the problem has been fixed, thank you very much.
