### ISSUE TITLE
Add support for coc-snippets

### ISSUE THREAD

**Issue by jdsutherland** [antoinemadec/coc-fzf#61]
It'd be nice if support was added for https://github.com/neoclide/coc-snippets.

**Comment by antoinemadec** [comment]
@jdsutherland , support for **snippets** with preview has been added.
Multi-select (populate quickfix window) is also supported if you want to open multiple snippets.

There are 3 tiny quirks:
1. preview has no syntax highlighting as bat does not support snippets
2. the json snippets added by coc always point to the first line of the file
3. some snippets previews are 1 line off

Overall this works great :smiley: 
Please let me know if you have any remarks/questions.

**Comment by jdsutherland** [comment]
@antoinemadec Thanks for adding this.

I've updated master and it doesn't seem to work.

`:CocFzfList snippets` results in
```log
Error on request (listLoadItems): Vim(return):Error invoking 'listLoadItems' on channel 3 (coc):
action "listLoadItems" not registered
```

**Comment by antoinemadec** [comment]
@jdsutherland i guess you are using coc.nvim release branch? If that's the case you have to use coc-fzf release branch as well. See Readme.

As soon as my PR (needed for snippet and other lists) is merged on coc.nvim release i will update coc-fzf release branch as well!

**Comment by jdsutherland** [comment]
Oops, I didn't realize I was using the release branch of coc.nvim.

It does, in fact, work great. Thanks!
