### ISSUE TITLE
Unable to open any CocFzfList

### ISSUE THREAD

**Issue by chinleung** [antoinemadec/coc-fzf#62]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
  - ```bat --version```: 0.15.4
  - Are your vim plugins up-to-date?:
  - ```(n)vim --version```:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
```

# Describe the Bug
When I try to open any CocFzfList, I get the following error:

![image](https://user-images.githubusercontent.com/19669331/91227708-fa104380-e6f4-11ea-8066-7ddcc8c7cc07.png)

It used to work previously but I'm not sure when it stopped working.

# To Reproduce
## **Minimal** vimrc
```vim
call plug#begin('~/.vim/plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf', {'do': 'yarn install --frozen-lockfile && yarn run build'}
call plug#end()

nnoremap <silent><nowait> <space>c :<C-u>CocFzfList commands<cr>
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. <kbd>space</kbd>+<kbd>c</kbd>

# Expected Behavior
The list of commands appearing in a FZF list.

**Comment by antoinemadec** [comment]
@chinleung it's because your are using Coc.nvim's 'release' branch.
See https://github.com/antoinemadec/coc-fzf#installation

Try this:
```vim
Plug 'antoinemadec/coc-fzf', {'branch': 'release'}
```

Please let me know if it fixes your issue :smiley:

**Comment by chinleung** [comment]
> @chinleung it's because your are using Coc.nvim's 'release' branch.
> See https://github.com/antoinemadec/coc-fzf#installation
> 
> Try this:
> 
> ```viml
> Plug 'antoinemadec/coc-fzf', {'branch': 'release'}
> ```
> 
> Please let me know if it fixes your issue 😃

Thanks! Using the `release` branch fixed my issue!

**Comment by fgheng** [comment]
> # Environment
> 
>     * `echo $FZF_DEFAULT_OPTS`:
> 
>     * `bat --version`: 0.15.4
> 
>     * Are your vim plugins up-to-date?:
> 
>     * `(n)vim --version`:
> 
> 
> ```
> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
> Compiled by brew@Catalina.local
> 
> Features: +acl +iconv +tui
> ```
> 
> # Describe the Bug
> 
> When I try to open any CocFzfList, I get the following error:
> 
> ![image](https://user-images.githubusercontent.com/19669331/91227708-fa104380-e6f4-11ea-8066-7ddcc8c7cc07.png)
> 
> It used to work previously but I'm not sure when it stopped working.
> # To Reproduce
> ## **Minimal** vimrc
> 
> ```viml
> call plug#begin('~/.vim/plugins')
> Plug 'neoclide/coc.nvim', {'branch': 'release'}
> Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
> Plug 'junegunn/fzf.vim'
> Plug 'antoinemadec/coc-fzf', {'do': 'yarn install --frozen-lockfile && yarn run build'}
> call plug#end()
> 
> nnoremap <silent><nowait> <space>c :<C-u>CocFzfList commands<cr>
> ```
> 
> ## Steps to Reproduce
> 
>     1. nvim -u minimal_vimrc
> 
>     2. space+c
> 
> 
> # Expected Behavior
> 
> The list of commands appearing in a FZF list.

hello, what fonts do you use?

**Comment by chinleung** [comment]
> hello, what fonts do you use?

I use [Dank Mono](https://dank.sh/), but it has shut down. 😄

**Comment by qiuyi116** [comment]
I have same problem, and change to branch release to match coc.nvim relase don't work.

**Comment by antoinemadec** [comment]
@qiuyi116 try updating your coc plugin.
If it still doesn't work, please open a new issue.
