### ISSUE TITLE
Extension list actions (enable, disable, etc)?

### ISSUE THREAD

**Issue by Frederick888** [antoinemadec/coc-fzf#67]
**Describe the solution you'd like**
Sorry if this has already been implemented. `CocList extensions` allows performing different actions on extensions. At the time of writing there are toggle, configure, open, disable, enable, lock, readme, reload, fix and uninstall. Is it possible to have these functions in coc-fzf as well? Currently it seems that coc-fzf is only able to toggle the selected extension if it's enabled.

**Describe alternatives you've considered**
Use CocList.

**Comment by antoinemadec** [comment]
Those actions are not implemented yet.

I am wondering, would it be a big deal if ```CocFzfList extensions``` was pointing to ```CocList extensions``` and would drop the FZF support?

I don't know if lists like ```extensions``` and ```services``` for instance, justify spending to much time to re-implement them in FZF.
Those don't use files and have a lot of features, the interest of using FZF is limited, although having a floating window is nice :smiley: 

Please let me know.
I might not be very responsive in the next 2 weeks as I am moving back to France, but I will try my best!

**Comment by Frederick888** [comment]
Yup that sounds good to me :) No one's gonna have hundreds of extensions I believe lol.

Thanks for the time and effort in maintaining this project!
