### ISSUE TITLE
Go to definition doesn't open in floating window

### ISSUE THREAD

**Issue by ludwj61** [antoinemadec/coc-fzf#68]
# Environment
Newest nightly nvim, fzf, coc. Newest bat.
Arch linux, alacritty.

# Describe the Bug
When calling coc-definition, e.g. through the example binding gd, the definition is not brought up in a floating window and instead jumps to the definition file like usual. 

This doesn't occur with any other option, e.g. coc-references.

**Comment by antoinemadec** [comment]
The definition is not supposed to be brought up in a floating window.
The floating window will pop when a function is defined in multiple files and we need to know in which file you wanna go.

This happens very often when looking for references. I hoe this helps !

Ps: please consider filling the template next time
