### ISSUE TITLE
CocFzfList actions not working

### ISSUE THREAD

**Issue by ryanhhtan** [antoinemadec/coc-fzf#69]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
--multi --reverse --preview-window=right:60% --height 100% --preview "bat --style=numbers --color=always --line-range :500 {}" --bind ?:toggle-preview --bind ctrl-space:toggle-preview --bind ctrl-j:preview-down --bind ctrl-k:preview-up --bind ctrl-s:toggle-sort

  - ```bat --version```:
bat 0.15.4

  - Are your vim plugins up-to-date?:
Yes

  - ```(n)vim --version```:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 28 2020 13:35:01)
Included patches: 1-1767
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk

```
(n)vim --version output
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 28 2020 13:35:01)
Included patches: 1-1767
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version without GUI.  Features included (+) or not (-):
+acl               -clipboard         -dnd               +gettext           +listcmds          -mouse_sysmouse    +postscript        +spell             +textobjects       +wildignore
+arabic            +cmdline_compl     -ebcdic            -hangul_input      +localmap          +mouse_urxvt       +printer           +startuptime       +textprop          +wildmenu
+autocmd           +cmdline_hist      +emacs_tags        +iconv             -lua               +mouse_xterm       +profile           +statusline        +timers            +windows
+autochdir         +cmdline_info      +eval              +insert_expand     +menu              +multi_byte        -python            -sun_workshop      +title             +writebackup
-autoservername    +comments          +ex_extra          +ipv6              +mksession         +multi_lang        +python3           +syntax            -toolbar           -X11
-balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          +tag_binary        +user_commands     -xfontset
+balloon_eval_term +cryptv            -farsi             +jumplist          +mouse             +netbeans_intg     +reltime           -tag_old_static    +vartabs           -xim
-browse            +cscope            +file_in_path      +keymap            -mouseshape        +num64             +rightleft         -tag_any_white     +vertsplit         -xpm
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +packages          -ruby              -tcl               +virtualedit       -xsmp
+byte_offset       +cursorshape       +float             +langmap           +mouse_gpm         +path_extra        +scrollbind        +termguicolors     +visual            -xterm_clipboard
+channel           +dialog_con        +folding           +libcall           -mouse_jsbterm     -perl              +signs             +terminal          +visualextra       -xterm_save
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +persistent_undo   +smartindent       +terminfo          +viminfo
-clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +popupwin          +sound             +termresponse      +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-0bnN0A/vim-8.2.1767=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U
_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_6
4-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
# Describe the Bug
:CocFzfList actions gets error: [coc-fzf] List actions does not exist.

# To Reproduce
## **Minimal** vimrc
```vim
" minimal vimrc
```
" Install the plugin manager itself
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install plugins {{{
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
Plug 'junegunn/fzf.vim' " needed for previews
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'antoinemadec/coc-fzf', {'branch': 'release'}
call plug#end()
" }}}

" Plugin Settings {{{

"" fzf
command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
nnoremap <silent> <space>f :Files<CR>

"" coc-nvim
""" Extensions
let g:coc_global_extensions = ['coc-java', 'coc-json', 'coc-python', 'coc-html', 'coc-xml', 'coc-emmet', 'coc-css', 'coc-snippets', 'coc-yaml', 'coc-tsserver', 'coc-tslint-plugin', 'coc-phpls', 'coc-highlight', 'coc-lists', 'coc-java-debug']

nnoremap <silent> <space><space> :<C-u>CocFzfList<CR>
"""" Show current action
nnoremap <silent> <space>a  :<C-u>CocFzfList actions<CR>
"""" Show most recent used buffers
" }}}

## coc-settings.json
{
  "snippets.userSnippetsDirectory": "/d/OneDrive/mysnips",
  "java.jdt.ls.vmargs": "-javaagent:/home/vagrant/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar",
  "java.home": "/home/vagrant/.sdkman/candidates/java/11.0.8-open",
  "java.configuration.runtimes": [
  {
    "name": "JavaSE-1.8",
    "path": "/home/vagrant/.sdkman/candidates/java/8.0.265-open",
    "default": true
  },
  {
    "name": "JavaSE-11",
    "path": "/home/vagrant/.sdkman/candidates/java/11.0.8-open"
  },
  {
    "name": "JavaSE-14",
    "path": "/home/vagrant/.sdkman/candidates/java/14.0.2-open"
  }
],
  "python.jediEnabled": false,
  "coc.preferences.colorSupport": true,
  "highlight.colors.enable": true,
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "java.format.settings.profile": "GoogleStyle",
  "java.maven.downloadSources": true,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
    "languageserver": {
        "kotlin": {
            "command": "/home/vagrant/code/kotlin-language-server/server/build/install/server/bin/kotlin-language-server",
            "filetypes": ["kotlin"]
        }
    }
}

## Steps to Reproduce
1.  create a spring demo project from https://start.spring.io
2. open the DemoApplication.java
3. delete the first line `package com.example.springdemo;`. coc.nvim will report issue found.
4. call :CocFzfList actions, get error response: [coc-fzf] List actions does not exist.

# Expected Behavior
Show the code action lists correctly as before. 
This issue may originate from 'coc-lists'. After a recent update, the ':CocList actions' became invalid. I am not sure this is an issue or a planned change in 'coc-lists'. If 'coc-list' no longer provide this source, is there any alternative solution?

**Comment by antoinemadec** [comment]
@ryanhhtan this is more of a coc.nvim issue.
I confirm ```:CocList actions``` is not available anymore.

As a temp workaround, you can do: ```:call coc_fzf#actions#fzf_run()```.
Please let me know if this work for you, in the meantime I will investigate the reason ```CocList actions``` is no longer available on coc.nvim.

**Comment by antoinemadec** [comment]
@ryanhhtan OK, so the new way to use actions is:
```vim
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
```

```CocList actions``` has been replaced by ```<Plug>(coc-codeaction)```.
It will display a nice popup window for you to choose from.

Do you prefer ```:call coc_fzf#actions#fzf_run()``` over ```<Plug>(coc-codeaction)```?
If so, why?

**Comment by ryanhhtan** [comment]
The :call coc_fzf#actions#fzf_run() works! Thank you so much for offering me the workaround solution. Personally, I prefer  :call coc_fzf#actions#fzf_run() over <Plug>(coc-codeaction) because the latter one can only offer to choose an action with a number or move the cursor to the item. If the list is very long, I would have to keep scrolling down to select the action I want which is really annoying. In contrast, FZF can easily filter out the action I want. Glad to get the function back, Thanks for your great job to build this amazing plugin!

**Comment by dansomething** [comment]
It looks like CocAction has been added as a replacement. https://github.com/neoclide/coc.nvim/commit/bab5d20a3fab70c977ceee4eaae7d8e91915c286

**Comment by antoinemadec** [comment]
> It looks like CocAction has been added as a replacement. [neoclide/coc.nvim@bab5d20](https://github.com/neoclide/coc.nvim/commit/bab5d20a3fab70c977ceee4eaae7d8e91915c286)

Yep, that works too!
I think I will re-introduce ```:CocFzfList actions``` in the next few days, it will be cleaner than ```:call coc_fzf#actions#fzf_run()```.
The commit is ready, I just need to test it.

**Comment by antoinemadec** [comment]
@ryanhhtan , @dansomething , I just reintroduced ```:CocFzfList actions```.
Feedback is welcome.

Keep in mind that:
  - ```:CocFzfList actions``` is equivalent to ```<Plug>(coc-codeaction)```, which runs actions **on the whole buffer**
  - ```CocAction``` is equivalent to ```<Plug>(coc-codeaction-selected)``` **when one line only is selected**

I hope this helps!

**Comment by expipiplus1** [comment]
Note that some of the results displayed by `CocAction` never appear in coc's action list (and hence never appear in coc-fzf's list).

It would be really great if coc-fzf were to have equivalents for `coc-codeaction-line` and `coc-codeaction-selected`

I do not know if the API presented by coc.nvim permits this easily though.

**Comment by expipiplus1** [comment]
Ah, looks like it is possible to get this list using `CocAction('codeActions', visualmode())`

**Comment by expipiplus1** [comment]
This patch appends actions specific to the current line to the list:

```diff
diff --git a/autoload/coc_fzf/actions.vim b/autoload/coc_fzf/actions.vim
index 439fbba..469ec20 100644
--- a/autoload/coc_fzf/actions.vim
+++ b/autoload/coc_fzf/actions.vim
@@ -4,7 +4,7 @@ let s:prompt = 'Coc Actions> '

 function! coc_fzf#actions#fzf_run() abort
   call coc_fzf#common#log_function_call(expand('<sfile>'), a:000)
-  let g:coc_fzf_actions = CocAction('codeActions')
+  let g:coc_fzf_actions = CocAction('codeActions') + CocAction('codeActions', 'n')
   if !empty(g:coc_fzf_actions)
     let expect_keys = coc_fzf#common#get_default_file_expect_keys()
     let opts = {
```

It uses the undocumented `'n'` feature. Better would be to use 'codeActionsRange' with the range of the current line!
