### ISSUE TITLE
Add clear error message when :CocFzfList {source} does not exist

### ISSUE THREAD

**Issue by antoinemadec** [antoinemadec/coc-fzf#7]
if a unsupported command is given (e.g. :CocFzfList foo), we should a better message (e.g. [coc.nvim] List dd not found like :CocList does) than throwing lines of unhandled stacktraces.

**Comment by wookayin** [comment]
Also: `:CocFzfList symbols --kind` (#5) without arguments should have better error message.

**Comment by wookayin** [comment]
Awesome!
