### ISSUE TITLE
Warning message each vim startup if bash is not in path

### ISSUE THREAD

**Issue by bratekarate** [antoinemadec/coc-fzf#70]
Great plugin! I have an issue however if bash is not available on the system.

As per the `fzf.vim` documentation, one should do `let g:fzf_preview_window = ''` to disable previews. But `coc-fzf` still calls `fzf#vim#with_preview` on startup, causing a non-avoidable warning each vim startup:
```
Preview window not supported (bash not found in PATH)
```
It would be great if this function is not called if `g:fzf_preview_window == ''`, as this means previews are disabled.

I solved this locally with the following changes:
```diff
diff --git a/after/plugin/coc_fzf.vim b/after/plugin/coc_fzf.vim
index 1d48b5c..98a4b7d 100644
--- a/after/plugin/coc_fzf.vim
+++ b/after/plugin/coc_fzf.vim
@@ -1,11 +1,16 @@
 " test other plugins availability
 
-let g:coc_fzf_preview_available = 1
-try
-  call fzf#vim#with_preview()
-catch
+if exists('g:fzf_preview_window') && !len(g:fzf_preview_window)
   let g:coc_fzf_preview_available = 0
-endtry
+else
+  let g:coc_fzf_preview_available = 1
+  try
+    call fzf#vim#with_preview()
+  catch
+    let g:coc_fzf_preview_available = 0
+  endtry
+endif
+
 
 if g:coc_fzf_preview_available
   augroup CocFzfLocation
```
I could issue a PR if there is any interest to merge this.

**Comment by antoinemadec** [comment]
@bratekarate , thanks a lot for the catch.
After reading fzf.vim code, what you say makes perfect sense.

Could you please issue a PR?
Your name will be featued in the repo: fame and prestige await you :smile: 

Cheers,
Antoine

**Comment by bratekarate** [comment]
> Your name will be featued in the repo: fame and prestige await you smile

Wow, that sounds almost irresistable :). I am very busy right now but will get to it as soon as I find time. Probably the weekend. I think I may be the only one that tried it on windows without bash anyway 😅

**Comment by antoinemadec** [comment]
Merged.
Thanks again!

**Comment by bratekarate** [comment]
My pleaasure! No popups anymore for me on windows :)
