### ISSUE TITLE
Support replace default key-binding, and support open in a new buffer.

### ISSUE THREAD

**Issue by orlandoxu** [antoinemadec/coc-fzf#72]
Hope open in new buffer default, or can replace it in vimrc.
Thx!!!

![image](https://user-images.githubusercontent.com/8287723/98629225-5decf480-2353-11eb-88c5-37254f927d33.png)

And, hope we can redefine s:default_action in vimrc.

**Comment by antoinemadec** [comment]
That sounds like a good idea, PR welcome (don't forget to update the help and readme).
Cheers !

**Comment by antoinemadec** [comment]
@orlandoxu thanks for the PR, but there is a better way to do this.
Just:
- update ```coc-fzf```, it won't work without my latest commit
- and then use:
```vim
    let g:fzf_action = {
      \ 'enter': 'edit',
      \ 'ctrl-t': 'tab split',
      \ 'ctrl-x': 'split',
      \ 'ctrl-v': 'vsplit' }
```

**Comment by orlandoxu** [comment]
Ok. Thx!!!

**Comment by antoinemadec** [comment]
@orlandoxu , the default command is now ```edit``` instead of ```buffer```.
No need to change ```g:fzf_layout``` anymore :wink:
