### ISSUE TITLE
some actions don't work

### ISSUE THREAD

**Issue by antoinemadec** [antoinemadec/coc-fzf#76]
# Describe the Bug
Actions using the popup window more than once don't work.

# To Reproduce
Selecting **Extract Method** in a python file should open a 2nd window asking you to name the method.

# Expected Behavior
Open a 2nd window to complete the action.

**Comment by antoinemadec** [comment]
@expipiplus1 , would you have time to take a look at this ?
My life is rather rock n roll these days and I don't have a minute to myself...

**Comment by expipiplus1** [comment]
What does coc itself do in this case? Could we just defer to that?

Not sure I have the time either to do this, especially since I don't have a use for it at the moment, also I'm very uncomfortable using vimscript :)

**Comment by antoinemadec** [comment]
Got it, chances are that this will also involve a PR on coc using typescript. Will take a look at it when I have time

**Comment by antoinemadec** [comment]
Closing because I don't see the error anymore.

**Comment by expipiplus1** [comment]
Cool :D glad that got sorted

**Comment by antoinemadec** [comment]
@expipiplus1 i guess they changed it in coc.nvim. If you see this issue coming back don't hesitate to open a new issue 🎉
