### ISSUE TITLE
"Go to anything"

### ISSUE THREAD

**Issue by kantord** [antoinemadec/coc-fzf#77]
**Is your feature request related to a problem? Please describe.**
There are many different ways to navigate a project. Sometimes it's not effective to only search in
one list at a time, as the correct result might be found in one of many different sources. Using 
different key bindings for different sources is not always effective.

**Describe the solution you'd like**
I would like to be able to search in multiple sources at once. Each item could be prefixed by the name of the
source they were found in.

**Describe alternatives you've considered**
Just using denite

**Comment by antoinemadec** [comment]
That would be super extremely tough to implement.
I took a look at coc-denite when I started this project and i didn't see this feature in it, did I miss something?

Each Coc list has a different way of treating its elements : some are files, some are actions etc. This would be a very tough thing to implement.

**Comment by antoinemadec** [comment]
Closing because seems not feasible. Thanks for taking time to open an issue though :)

**Comment by kantord** [comment]
I managed to find a way to achieve something quite similar - although not with fzf.

You need [denite.nvim](https://github.com/Shougo/denite.nvim) and a couple sources.

Then you can create this mapping:

```
nnoremap <C-G> :<C-u>DeniteProjectDir buffer file_mru coc-workspace coc-command file/rec help -start-filter<CR>
```

buffer can list open buffers
file_mru can list most recent files
coc-workspace can list symbols(tags) in your project
coc-command is commands
file/rec for all your project files
help for vim help

that's pretty much all I need from go to anything!

It's also possible to put live grep there

**Comment by antoinemadec** [comment]
@kantord ok, does it this require to install coc-denite or is it working out of the box ?

**Comment by kantord** [comment]
@antoinemadec it requires [coc-denite](Plug 'neoclide/coc-denite'), and the latest version, [as this bug was just fixed](https://github.com/neoclide/coc-denite/issues/9).

You'll also need this:

```
Plug 'Shougo/neomru.vim'
```

which supplies `file_mru`.

**Comment by kantord** [comment]
I am using this config:

```
highlight DeniteFilter ctermbg=4 ctermfg=0
highlight DeniteMatch ctermbg=1 ctermfg=0 cterm=bold

" denite
call denite#custom#option('_', {
      \ 'prompt': '',
      \ 'split': 'floating',
      \ 'wincol': &columns / 6,
      \ 'winwidth': &columns * 2 / 3,
      \ 'winrow': &lines / 6,
      \ 'winheight': &lines * 2 / 3,
      \ 'highlight_filter_background': 'DeniteFilter',
      \ 'highlight_matched_range': 'DeniteMatch',
      \ 'highlight_matched_char': 'DeniteMatch',
      \ 'highlight_preview_line': 'DeniteMatch',
      \ 'highlight_prompt': 'NormalFloat',
      \ 'highlight_window_background': 'NormalFloat',
      \ 'max_dynamic_update_candidates': 100000
      \ })

call denite#custom#var('file/rec', 'command',
      \ ['rg', '--files'])
call denite#custom#source('_', 'matchers', ['matcher/fruzzy'])
call denite#custom#source('_', 'sorters', ['sorter/sublime'])
call denite#custom#source(
	\ 'file_mru', 'matchers', ['matcher/fuzzy', 'matcher/project_files'])

autocmd FileType denite call s:denite_settings()

function! s:denite_settings() abort
  nnoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> <C-v>
        \ denite#do_map('do_action', 'vsplit')
  nnoremap <silent><buffer><expr> d
        \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
        \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> <Esc>
        \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> q
        \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
        \ denite#do_map('open_filter_buffer')
endfunction

autocmd FileType denite-filter call s:denite_filter_my_settings()

function! s:denite_filter_my_settings() abort
	  inoremap <silent><buffer> <C-j>
	  \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
	  inoremap <silent><buffer> <C-k>
	  \ <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
  inoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
  inoremap <silent><buffer><expr> <Esc>
        \ denite#do_map('quit')
endfunction

let g:fruzzy#usenative = 1
```

this will more or less simulate fzf behavior: you are instantly in fuzzy search, and <C-J> <C-K> can be used to move up and down

**Comment by antoinemadec** [comment]
@kantord , as previously said, it would be a pain to implement in FZF.

The reason that each FZF list parses and handle the information differently depending on what is in the FZF terminal window.
We would need to add info on which list each line correspond to.

Also, so list as very slow (like git issues for instance).
That would make this feature very unpractical.

In conclusion, I guess you are stuck with coc-denite if you need this feature.
Sorry, and thanks for taking time to create this issue.
