### ISSUE TITLE
Support ranges for CocFzfList(actions)

### ISSUE THREAD

**Issue by expipiplus1** [antoinemadec/coc-fzf#79]
It would be great to permit running CocFzfList(actions) with a range, then the user could make a visual selection and then get the list of actions for that range. This turns out to be important sometimes for language servers which are a bit particular about when they return code actions.

coc supports this with `coc-codeaction-selected` (similar to `coc-codeaction-line`)

Probably pairs nicely with https://github.com/antoinemadec/coc-fzf/pull/74

I know nothing about vimscript, but I guess this shouldn't be too complicated a change. Just tell vim that ranges are allowed and pass `visualmode()` to `CocAction`

**Comment by antoinemadec** [comment]
Sounds good to me, PR welcome.

**Comment by expipiplus1** [comment]
I've added this functionality to my PR here: https://github.com/antoinemadec/coc-fzf/pull/74

I am not good at vimscript
