### ISSUE TITLE
Issue opening up file selector

### ISSUE THREAD

**Issue by appelgriebsch** [antoinemadec/coc-fzf#80]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```: ""
  - ```bat --version```: bat 0.16.0
  - Are your vim plugins up-to-date?:
  - ```(n)vim --version```:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

# Describe the Bug
I've added some overwrites for files, buffers and such to my vimrc:

```vim
...
call coc_fzf#common#add_list_source('files', 'display files', 'Files')
call coc_fzf#common#add_list_source('gfiles', 'display git files', 'GFiles')
...
```
This was working perfectly just some days ago, but looks like with the recent update of the plugin this is broken....

* triggering CocFzfList files returns with an error: Invalid directory
* triggering CocFzfList gfiles just shows an empty list

Quite interestingly running the commands themselves, such as Files or GFiles will deliver the expected fzf list (of files in the directory / in Git).

Has the semantic of the add_list_source changed recently?

# To Reproduce
## **Minimal** vimrc
```vim
" minimal vimrc
call coc_fzf#common#add_list_source('files', 'display files', 'Files')
call coc_fzf#common#add_list_source('gfiles', 'display git files', 'GFiles')

" Using CocList
nnoremap <silent> <space><space> :<C-u>CocFzfList<CR>
" Show files
nnoremap <silent> <space>f  :CocFzfList files<cr>
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. ```:e myfile.py```
3. etc

# Expected Behavior
When triggering the files or gfiles list it should come up with the same output that is created when running Files or GFiles from the vim command prompt.

**Comment by antoinemadec** [comment]
@appelgriebsch thanks a lot for taking the time to report this issue :heart: 
It should be fixed now.

Please reopen if the problem persists.
