### ISSUE TITLE
List references doesn't put buffer in buffer list.

### ISSUE THREAD

**Issue by ZacharyRizer** [antoinemadec/coc-fzf#81]
Quick question. Is it normal behavior for the buffer to not be listed when opening from the Coc-References. Meaning that if I press 'gr' to get-references, it shows them nicely in the fzf menu, and if I press enter on one, it takes me to that buffer. But if I leave that buffer, it is no longer listed in my buffer list. Is this the default behavior? If so, is there a setting to make it stay in my buffer list? Thanks.

**Comment by antoinemadec** [comment]
Nope, it was legacy code that made it through all the successive commits.
Please reopen if it persists.

**Comment by ZacharyRizer** [comment]
Thanks for the fast response! I just updated the plugin, but I'm still not seeing it in my buffer list. To get it to stick to my buffer list I have to open it up separately using something netrw or coc-explorer.
