### ISSUE TITLE
`:CocFzfList` conflicts with `g:fzf_action`

### ISSUE THREAD

**Issue by Nadrieril** [antoinemadec/coc-fzf#82]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```: --height 40% --reverse --inline-info
  - ```bat --version```: bat 0.17.1
  - Are your vim plugins up-to-date?: updated everything a few days ago
  - ```(n)vim --version```:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
```

# Describe the Bug

For my non-coc fzf.vim usage, I have configured
```vim
let g:fzf_action = {
  \ '': 'SmartTabEdit',
  \ 'ctrl-e': 'e',
  \ 'ctrl-t': 'tabe',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```
Where `SmartTabEdit` is a custom command that jumps to a file if it's already open or opens it in a new tab otherwise.
The problem is that when I run `:CocFzfList list` or `:CocFzfList commands` or some other list that doesn't list files, coc-fzf clearly tries to call `SmartTabEdit` and errors with:
```
Error detected while processing function 139[30]..<SNR>41_callback:
line   21:
Vim:E471: Argument required: silent SmartTabEdit
Press ENTER or type command to continue
```

# To Reproduce
## **Minimal** vimrc
```vim
let g:fzf_action = { '': 'SmartTabEdit' }
command! -nargs=1 -complete=file SmartTabEdit call <SID>smarttabedit("<args>")
function! s:smarttabedit(file)
  exe 'tabe '.a:file
endf
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. `:CocFzfList list`
3. select any entry in the list

# Expected Behavior
I expect coc-fzf to not use `g:fzf_action` when it's not listing files. One way would be to provide a custom `sink`. Another way would be to not use `fzf#wrap`.

**Comment by antoinemadec** [comment]
@Nadrieril , thanks for taking time to open this issue (and to follow the template ❤️ ).
It should work like a charm now, please let me know.
For info, this bug was only showing on ```:CocFzfList list```.

**Comment by Nadrieril** [comment]
Nice, that fixes `:CocFzfList list` indeed! I still have the issue for `:CocFzfList actions` and `:CocFzfList command` however

**Comment by antoinemadec** [comment]
@Nadrieril , yas indeed. It should be fixed for good now.
Thanks!

**Comment by Nadrieril** [comment]
Perfect, it works! Thanks for your quick reaction!
