### ISSUE TITLE
coc-fzf fails to work with builtin functions (coc-definition, cic-implementations etc) when g:fzf_preview_window is set to [] 

### ISSUE THREAD

**Issue by smypf** [antoinemadec/coc-fzf#83]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
```--height 40%```
  - ```bat --version```:
```bat 0.17.1```
  - Are your vim plugins up-to-date?:
Yes
  - ```(n)vim --version```:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info
```

# Describe the Bug
When disabling the preview window with `let g:fzf_preview_window = []` as described in the fzf manual the functionality no longer works, defaulting back to default behaviour.

# To Reproduce
## **Minimal** vimrc
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
Plug 'junegunn/fzf.vim' " needed for previews
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
Plug 'antoinemadec/coc-fzf'

call plug#end()

" Empty value to disable preview window altogether
" Commenting out this line restores the expected behaviour
let g:fzf_preview_window = []


nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. ```:e myfile.tsx```
3. Attempt to view references of any function using `gr`

# Expected Behavior
The references must be shown in a fzf window without a file preview.

**Comment by antoinemadec** [comment]
@smypf , thanks for the report.
I did not think someone would want the location lists (reference, definition etc) through FZF without the preview, but this is a completely use case.

Please let me know if you encounter further issues.

**Comment by smypf** [comment]
Thanks for taking the time to fix this @antoinemadec. I really like the interface that coc-fzf presents results in and the ease of using it over the standard implementation.

In regards to my usage when looking for a reference I want to find where it is in a particular file so the preview is unnecessary. I also don't like it since I think it adds visual clutter.
