### ISSUE TITLE
Use buffer for preview window instead of the file.

### ISSUE THREAD

**Issue by NikoKS** [antoinemadec/coc-fzf#87]
**Is your feature request related to a problem? Please describe.**
Currently, when opening coc-reference, the preview window tries to open the file instead of the buffer. Is there an option to make the preview to show the buffer instead? This causes problems like:

unable to open reference for new file
![Screen Shot 2021-01-14 at 9 59 35 AM](https://user-images.githubusercontent.com/24285511/104631140-aa54f900-5650-11eb-89bc-111c8d08b220.png)

and misaligned preview on an unsaved file
![Screen Shot 2021-01-14 at 10 13 12 AM](https://user-images.githubusercontent.com/24285511/104631482-294a3180-5651-11eb-87ab-ab1d6d3e0829.png)

I have not tried on other functionality other than reference, but I imagine functions like diagnostics would also benefit from this.

**Describe the solution you'd like**
Is it possible to open the buffer as a preview instead by default or as an option? That should fix this problem

Thank you.

**Comment by antoinemadec** [comment]
Thanks for reporting this issue.
I don't think it is doable as the preview script opens a file outside vim and does not have the view of vim's current buffers.

If you find a way to circumvent that, please reopen this issue.

Cheers 🥂
