### ISSUE TITLE
Terminal mode regression in NVIM v0.5.0-dev+3706-g8950f4e94

### ISSUE THREAD

**Issue by oxilumin** [antoinemadec/coc-fzf#89]
In some latest version of nvim there seems to be a regression from https://github.com/neovim/neovim/issues/12246 that causes coc-fzf to not restore insert mode in multilevel coc-fzf menus (like services/actions/etc.)
Can't we check whether mode() returns "n" or "t" as a condition instead?

https://github.com/antoinemadec/coc-fzf/blob/a8b32b8b8a37d7fb87687c0187b7ad36987e2122/autoload/coc_fzf/common.vim#L21

**Comment by antoinemadec** [comment]
@oxilumin , this is in fact a regression coming from FZF itself: https://github.com/junegunn/fzf/commit/1a76bdf8914195ab26ebac7e49a3ed8752dd69bd

Reverting this commit fixes it.
I just opened an issue here: https://github.com/junegunn/fzf/issues/2352
