### ISSUE TITLE
Can't use CocFzfList as command because it is ambiguos

### ISSUE THREAD

**Issue by danielo515** [antoinemadec/coc-fzf#9]
Hello,
Thanks for this plugin. It is a life saver.
My normal use case would be to just trigger the main list, and navigate from there. However, the base command CocFzfList is ambiguous because it's name is a substring of all the others. Would it be possible to rename it so this is not the case?
Thanks!

**Comment by antoinemadec** [comment]
Hi @danielo515 , thanks a lot :smile: 

Two days ago, I modified the commands to on have one left:
```vim
:CocFzfList {source}
```

It now behaves exactly like ```CocList```.

Are you up to date? Does this fix your issue? If not, could you please give me a concrete example of the commands you run and the problem you are facing?

Cheers,
Antoine

**Comment by danielo515** [comment]
Just run PlugUpdate, and that fixed my problem. Awesome.
For one seconds, when I hit tab and saw that I was able to select multiple values I thought that I can open several ones, but that is not possible, right?

**Comment by antoinemadec** [comment]
@danielo515 , nope, ```:CocFzfList``` opens only 1 list at a time (like ```:CocList```).
The command completion won't propose you to enter a second list.

**Comment by danielo515** [comment]
> The command completion won't propose you to enter a second list.
Not sure what do you mean by that. Chaining lists (list that open other lists) works, if that is what you mean

**Comment by antoinemadec** [comment]
@danielo515 , I think we talk about 2 different things.
I meant that, for example, ```:CocFzfList commands diagnostics``` is not supported.
After writing ```:CocFzfList commands```, the completion (pressing tab) won't propose ```diagnostics``` since it is not supported to display 2 lists at the same time.

**Comment by danielo515** [comment]
Ah, OK.
Thanks for the clarification
