### ISSUE TITLE
"E37: No write since last change (add ! to override)" occurs when opening edited file

### ISSUE THREAD

**Issue by rainzm** [antoinemadec/coc-fzf#90]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```:
  
  - ```bat --version```:
  bat 0.15.4
  - Are your vim plugins up-to-date?:
  yes
  - ```(n)vim --version```:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
编译者 travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/share/nvim"

Run :checkhealth for more info
```

# Describe the Bug
Use `CocFzfList diagnostics` or `<Plug>(coc-references)` to open FzfList window and select a file to open. If this file has been modified and not saved, "E37: No write since last change (add ! to override)" will occurs.

I noticed the modification in commit https://github.com/antoinemadec/coc-fzf/commit/94103981228454680736c2d728862ec4616cd3ac and `edit` a file that has been modified but not saved will have the above error.
I roll the commit above and the problem disappears.
# To Reproduce
## **Minimal** vimrc
```vim
" minimal vimrc
```

## Steps to Reproduce
1. `CocFzfList diagnostics`
2. select a file that has been modified but not saved
3. error occurs

# Expected Behavior
no error

**Comment by antoinemadec** [comment]
@rainzm thanks a lot for reporting this issue.
I will try to take a look at it in the next few days !
