### ISSUE TITLE
Error when there are no actions

### ISSUE THREAD

**Issue by stellarhoof** [antoinemadec/coc-fzf#91]
# Describe the Bug

`CocFzfList actions` fails if there are no actions

```
Error on request (codeActions): Vim(return):Error invoking 'codeActions' on channel 3 (coc):
Mode 'n' not supported
Error detected while processing function coc_fzf#lists#fzf_run[7]..<SNR>74_run_source[8]..coc_fzf#actions#fzf_run:
line    8:
E712: Argument of filter() must be a List or Dictionary
```

**Comment by antoinemadec** [comment]
Please fill the bug template with precise instructions and minimal vimrc to reproduce.

**Comment by antoinemadec** [comment]
@stellarhoof this should work just fine now.
The issue was that the arguments to get the line actions actions have recently changed.

Please consider following the bug template next time, that would have sped up my debug.
It is there for a reason.

Thanks in advance :smiley:

**Comment by stellarhoof** [comment]
@antoinemadec Apologies. I was going to use the template when I saw your message but got bogged down at work.
