### ISSUE TITLE
Do not block if LSP server has not finished starting up

### ISSUE THREAD

**Issue by stellarhoof** [antoinemadec/coc-fzf#92]
**Is your feature request related to a problem? Please describe.**

Open a file where LSP takes a while to startup and immediately invoke `CocFzfList`. It blocks the UI until the server is done.

**Describe the solution you'd like**

Not block the UI. Perhaps even display an error message saying that the server is starting up.

**Comment by antoinemadec** [comment]
Please fill the bug template with precise instructions and minimal vimrc to reproduce.

**Comment by antoinemadec** [comment]
@stellarhoof closing since I don't knoow how to reproduce it,
Feel free to open a new issue if you have a minimal vimrc and steps to reproduce this.
