### ISSUE TITLE
CocList fallbacks either insert a redundant 'i' or leave vim in insert mode

### ISSUE THREAD

**Issue by Frederick888** [antoinemadec/coc-fzf#93]
# Environment
  - ```echo $FZF_DEFAULT_OPTS```: _(null)_
  - ```bat --version```: `0.18.0`
  - Are your vim plugins up-to-date?: Yes
  - ```(n)vim --version```: 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210210-5325-1nkdpus/neovim-0.4.4/build/config -I/tmp/neovim-20210210-5325-1nkdpus/neovim-0.4.4/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210210-5325-1nkdpus/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210210-5325-1nkdpus/neovim-0.4.4/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4_1/share/nvim"

Run :checkhealth for more info
```

# Describe the Bug
Some lists at the moment redirects to CoC's built-in `CocList`.

If I use such a list from `CocFzfList` (without arguments, then choose from the pop-up), either a redundant `i` is inserted into the fuzzy search bar, or after Esc it leaves vim in insert mode.

# To Reproduce
## **Minimal** vimrc
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

" vim-plug
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'antoinemadec/coc-fzf', { 'branch': 'release' }

call plug#end()
```

## Steps to Reproduce
1. nvim -u minimal_vimrc
2. ```:CocFzfList```
3. Choose a list like `folders`

# Expected Behavior
No redundant `i` and after ESC Vim should be in normal mode.

---

Commenting out https://github.com/antoinemadec/coc-fzf/blob/3c8ca6127af51768cad8ff1074db5a9713d7fe13/autoload/coc_fzf/lists.vim#L70 seems to fix the problem for me. Now both lists with native coc-fzf support (e.g. `commands`) and non-natives (e.g. `folders`) work normally. Not sure if this is the root reason though.

**Comment by antoinemadec** [comment]
Fzf has changed recently and it is probable that the enter_term_mode() hack is not needed anymore on neovim 0.4.4.

I will remove it in the next few days.
