### ISSUE TITLE
Feature request: Support `--kind` for `outline` as well

### ISSUE THREAD

**Issue by lanza** [antoinemadec/coc-fzf#95]
You've implemented `--kind` for symbols but the feature also exists for the `outline` CocList type. This would also be very useful.

**Comment by antoinemadec** [comment]
Is this also a feature of CocList ?

**Comment by lanza** [comment]
> Is this also a feature of CocList ?

[Yup, see here.](https://github.com/neoclide/coc.nvim/blob/bf98939a8cdaee5a0d9dbc70610660e5298075d7/src/list/source/outline.ts#L24).

**Comment by antoinemadec** [comment]
Cool, definitely a feature i will add in the near future !
