### ISSUE TITLE
The border is not displayed.

### ISSUE THREAD

**Issue by nakai-tsuyoshi** [antoinemadec/coc-fzf#99]
![non-border](https://user-images.githubusercontent.com/82267684/120072304-2dda2880-c0ce-11eb-9df7-515c90a318d0.png)
I'm using neovim on wsl2 (Ubuntu).
As shown in the image above, the border is not displayed. I also tried it on native Ubuntu 20.0.4 and it was the same.
When I try it on mac OS with the exact same init.vim, plugin, and providers' versions (e.g. python3.9.4, ruby 3.0.1), however, the borders do show up.
What could be the cause? No other problems have occurred except for the appearance.

**Comment by antoinemadec** [comment]
@nakai-tsuyoshi please follow the issue template, **minimal** vimrc, steps to reproduce etc.
Without it, i won't be able to help you.

**Comment by nakai-tsuyoshi** [comment]
@antoinemadec 
I'm sorry.
No special settings were required to reproduce this. Here is the enviroment I checked and the minimal init.vim.

OS: Ubuntu (WSL2) on Windows
neovim version: NVIM v0.5.0-dev+1330-gd16e9d8ed (.appimage)
providers' versions: python 3.9.4 (pyenv 0.4.3), Node.js v14.17.0 (neovim 4.10.0), yarn 1.22.10

minimal init.vim
```vim
set encoding=utf-8
set hidden
set nobackup
set nowritebackup

let g:python3_host_prog = expand('path/to/python3')

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
Plug 'junegunn/fzf.vim' " needed for previews
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'antoinemadec/coc-fzf', {'branch': 'release'}
call plug#end()

" Mapping for CocFzfList
nnoremap <silent> <F1> :<C-u>CocFzfList<CR>
```

Pressed F1, I saw a window without border.

**Comment by antoinemadec** [comment]
@nakai-tsuyoshi , thanks for the minimal vimrc.

I was not able to reproduce you issue on Linux with ```nvim v0.5.0-dev+1233-g82ac44d01```.
Chances are that this is a FZF issue with windows.

Could you please try the following command: ```:FZF```.
Do you see the same problem? If so you should consider searching for/creating a ticket directly on fzf or fzf.vim.

**Comment by nakai-tsuyoshi** [comment]
@antoinemadec Thanks.
When I tried the command `:FZF`, the same issue occurred. I'll check fzf.

**Comment by nakai-tsuyoshi** [comment]
I have found the cause of this issue.
Windows Terminal was misbehaving.

**Comment by antoinemadec** [comment]
@nakai-tsuyoshi was is fixed in FZF or was it fixed in your Windows config?

**Comment by nakai-tsuyoshi** [comment]
@antoinemadec
I made a mistake reopening it.
I was using "Windows Terminal" developed by Microsoft as the terminal app. When I tried using the default WSL2 terminal, however, this issue didn't occur.
In other word, it was a terminal problem. I'm wondering if I should switch apps or just be patient, since I can't seem to fix it in the settings.

**Comment by nakai-tsuyoshi** [comment]
@antoinemadec That comment was not accurate and will be corrected.
The default terminal for WSL2 also displayed a bit oddly, so I checked it out.
When I changed the font to MesloLGS NF, it was displayed nicely in the Windows Terminal ! It seems that the fonts used were incompatible.

![image](https://user-images.githubusercontent.com/82267684/120181078-884ac480-c247-11eb-80cd-dc3c9ed9ad37.png)
